packages:
  - "apps/*"
  - "packages/*"
  - "examples/*"

allowBuilds:
  '@reown/appkit': false
  bigint-buffer: false
  bufferutil: false
  core-js: false
  esbuild: true
  protobufjs: false
  sharp: true
  utf-8-validate: false

overrides:
  '@noble/hashes': ^1.8.0
  '@dynamic-labs-wallet/primitives': 0.0.337
